spring.application.name=university-media-monitoring-system

spring.datasource.url=jdbc:postgresql://localhost:5432/otfiv_web
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driverClassName=org.postgresql.Driver

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.hibernate.ddl-auto=create

spring.mail.host=mail.edu.uz
spring.mail.port=465
spring.mail.username=press@edu.uz
spring.mail.password=9dc14fOe5

spring.mail.properties.mail.smtp.from=press@edu.uz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true



logging.level.org.springframework.security=DEBUG

exception.telegram.bot.chat.id=5033574248
exception.telegram.bot.token=6481582209:AAEF7F3X55crX-KfOY7nTMHtSx_tG6Jxj-w

url=https://pressa.e-edu.uz/repassword?token=

server.http2.enabled=true