spring.application.name=university-media-monitoring-system

spring.datasource.url=jdbc:postgresql://localhost:5432/otfiv_web
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driverClassName=org.postgresql.Driver